### ISSUE TITLE
Custom complete issue with scheduled notification 

### ISSUE THREAD

**Issue by bw352** [ksalzke/scheduling-omnifocus-plugin#10]
What I did: 
- Used "custom complete" plug-in to complete a daily repeating task with the Today tag, defer date, scheduled notification, and no due date. 

What happens as expected:
- Removes Today tag, marks the task as done

What doesn't happen:
- Remove the scheduled notification associated with the original defer date, which means the completed task still stays visible in Forecast perspective.

**Comment by ksalzke** [comment]
Thanks @bw352! Should now be fixed by ksalzke/custom-complete-omnifocus-plugin@e2fc97ad36d991209f1a7f59fad0d3b060b06446
