### ISSUE TITLE
Schedulling task at 1 Sep 2023 will match the 11 Sep 2023 tag

### ISSUE THREAD

**Issue by Wesseldr** [ksalzke/scheduling-omnifocus-plugin#11]
OmniFocus: 3.14.4 (v151.31.16) / OsX: 13.5 M1
Scheduling plugin: 2.3.0

Region Settings:
<img width="464" alt="image" src="https://github.com/ksalzke/scheduling-omnifocus-plugin/assets/4012809/1671e695-4836-4f67-aba4-dc7ef6ba9417">
 
Steps to reproduce:
1. Create a new task inside a project
2. Mark the task as Focus (star)
3. No due dates, No deffer no repeats. Just clean task
4. Schedule the task at: 11 Sep 2023 with the scheduler automation plugin set the string to: "11 Sep 2023" press enter and the task is scheduled at that time.

Expected Result: Task is scheduled at 11 Sep 2023, and a tag is created in the schedule tree with the 11 Sep 2023 date.

Create a new empty task:
1. Create a new task inside a project
2. Mark the task as Focus (star)
3. No due dates, No deffer no repeats. Just clean task
4. Schedule the task at: 1 Sep 2023 with the scheduler automation plugin set the string to: "1 Sep 2023" press enter and the task is scheduled at "11 Sep 2023" (mmm)

Expected: task is scheduled at 1 Sep 2023, it reuses the 11 Sep 2023 tag and sets the task at 11 Sep instead of 1 Sep 2023

There is  no workaround like renaming it with tmp_ just keeps being matched, deleting the tag 11 Sep 2023 will enable again to schedule a task at 1 Sep 2023 again..

Bit puzzled, if I find some additional clue's I'll add it here.. 

Wes

**Comment by ksalzke** [comment]
Thanks so much for the bug report @Wesseldr!

I found the issue (the plug-in was only looking for a tag that contained the date string i.e. 1 Sep 2023) and so was matching when it already found 11 Sep 2023)

So I've fixed that logic and hopefully should work as expected in the just-updated version.

Thanks again!

**Comment by Wesseldr** [comment]
That's fast :-)

Thank you for your swift action.. 
Yesss! Working!! ✅ release 2.3.1

Kind Regards,

Wes
"No matter where you go, there you are" from Buckaroo Banzai
